# config.yaml

# =========================
# 1. Data Configuration
# =========================

# Default date range for historical data
data:
  start_date: "2023-01-01"
  end_date: "2024-01-01"

# =========================
# 2. Paths Configuration
# =========================

# Data paths
paths:
  raw_data: "data/raw"             # Directory to store raw fetched data
  processed_data: "data/processed" # Directory to store processed data

# =========================
# 3. Output Configuration
# =========================

# Output settings
output:
  excel_path: "data/processed/optimized_portfolio.xlsx"  # Path to save the portfolio allocation and risk metrics

# =========================
# 4. Logging Configuration
# =========================

# Logging settings
logging:
  level: "INFO"                  # Logging level; options: DEBUG, INFO, WARNING, ERROR, CRITICAL
  file: "logs/app.log"           # Path to the log file

# =========================
# 5. Scraping Configuration
# =========================

# Scraping settings
scraping:
  wikipedia_url: "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"  # URL to fetch S&P 500 tickers and sectors

# =========================
# 6. Model Configuration
# =========================

# Model settings
model:
  optimization:
    risk_free_rate: 0.04             # Risk-free rate for Sharpe ratio calculation
    confidence_level: 0.95           # Confidence level for VaR calculation
    method: "long_short"             # Optimization method; options: "mean_variance", "minimum_variance", "maximum_sharpe", "risk_parity", "long_short"
    objective: "maximize_sharpe"     # Optimization objective; applicable for "long_short"; options: "maximize_sharpe", "minimize_risk"
    long_short_ratio: 1.0            # Ratio of total long positions to total short positions; applicable for "long_short"

# =========================
# 7. Screening Configuration
# =========================

# Screening settings
screening:
  # No thresholds needed; screening will be based on composite scores
  sectors:
    Information Technology: {}
    Health Care: {}
    Financials: {}
    Consumer Discretionary: {}
    Consumer Staples: {}
    Energy: {}
    Industrials: {}
    Materials: {}
    Real Estate: {}
    Utilities: {}
    Communication Services: {}
    # Add other sectors as needed

# =========================
# 8. Scoring Configuration
# =========================

# Scoring settings
scoring:
  metrics:
    - 'Trailing P/E'
    - 'Return on Equity'
    - 'Quarterly Earnings Growth'
    - 'Debt to Equity'
    - 'Dividend Yield'
  weights:
    - -1  # Lower P/E is better
    - 1   # Higher ROE is better
    - 1   # Higher Earnings Growth is better
    - -1  # Lower Debt to Equity is better
    - 1   # Higher Dividend Yield is better
  num_long: 5
  num_short: 5

# =========================
# 9. Rebalancing Configuration
# =========================

# Rebalancing settings
rebalance:
  frequency: "monthly"      # Rebalancing frequency; options: "daily", "weekly", "monthly"
  day_of_week: "monday"     # Relevant for weekly rebalancing
  day_of_month: 1           # Relevant for monthly rebalancing

# =========================
# 10. Additional Configurations
# =========================

# (Add any additional configuration sections here as your project evolves)
